import type { Metadata } from "next";
import { LegalShell, Section, ReviewNote, Ul } from "../_legal";
import { SUPPORT_EMAIL } from "@/lib/contact";

export const metadata: Metadata = {
  title: "Privacy Policy | Klova",
  description: "How Klova collects, uses, and protects your personal information.",
};

export default function PrivacyPage() {
  const emailDisplay = SUPPORT_EMAIL || "[email not set, update lib/contact.ts]";
  const emailHref = SUPPORT_EMAIL ? `mailto:${SUPPORT_EMAIL}` : "#";

  return (
    <LegalShell title="Privacy Policy" lastUpdated="June 2026">

      <Section heading="1. Who controls your data">
        <p>
          Klova is the data controller for personal information collected through this platform. We are
          registered in Nigeria and process your data in accordance with the Nigeria Data Protection
          Act 2023 (NDPA) and the regulations issued by the Nigeria Data Protection Commission (NDPC).
        </p>
        <ReviewNote>
          Insert the full registered company name and RC number before launch. A lawyer should also
          confirm whether Klova is required to file a data processing audit with the NDPC at your
          current scale, and whether a Data Protection Officer (DPO) must be formally appointed.
        </ReviewNote>
      </Section>

      <Section heading="2. What we collect">
        <p>When you use Klova, we collect the following information:</p>
        <p className="font-medium pt-1" style={{ color: "var(--text-strong)" }}>Information you give us directly:</p>
        <Ul items={[
          "Your first name, last name, phone number, and email address",
          "The address of the property to be cleaned",
          "Your service preferences (type of clean, number of bedrooms, add-ons)",
          "Ratings and reviews you submit after a booking",
          "Messages you send to our support team",
        ]} />
        <p className="font-medium pt-1" style={{ color: "var(--text-strong)" }}>Information generated by your booking:</p>
        <Ul items={[
          "Booking reference, date, status, and payment confirmation reference",
          "Which cleaner was assigned to your booking",
          "Whether order protection was selected",
        ]} />
        <p>
          We do not store your card number, card expiry, or CVV. Payment card data is handled
          entirely by Paystack and never passes through our servers.
        </p>
      </Section>

      <Section heading="3. Why we collect it">
        <p>We use your information to:</p>
        <Ul items={[
          "Create and manage your booking",
          "Match you with the most suitable available cleaner",
          "Send you booking confirmations, reminders, and updates",
          "Enable your cleaner to find and access your property",
          "Process refunds and handle complaints",
          "Respond to your support requests",
          "Detect and prevent fraud and misuse of the platform",
          "Improve the platform using anonymised, aggregated usage data",
          "Meet our legal, tax, and regulatory obligations in Nigeria",
        ]} />
        <p>
          We do not use your information for unsolicited marketing, and we do not sell or
          rent your data to any third party.
        </p>
      </Section>

      <Section heading="4. Who we share your data with">
        <p>
          We share your information only where it is necessary to complete the service or where
          the law requires it.
        </p>
        <p className="font-medium pt-1" style={{ color: "var(--text-strong)" }}>Service providers we use:</p>
        <Ul items={[
          "Paystack: processes your payment. Your card data is governed by Paystack's privacy policy.",
          "Termii: delivers booking confirmations and status updates to your phone number.",
          "Supabase: hosts our database. Your data is stored on their secure cloud infrastructure.",
          "Vercel: hosts our website. General web traffic passes through their platform.",
        ]} />
        <p className="font-medium pt-1" style={{ color: "var(--text-strong)" }}>Your assigned cleaner:</p>
        <p>
          When a cleaner is matched to your booking, they receive your first name and property
          address only. They do not receive your surname, email address, phone number, or any
          payment information.
        </p>
        <p className="font-medium pt-1" style={{ color: "var(--text-strong)" }}>Legal and regulatory authorities:</p>
        <p>
          We will disclose information to Nigerian government or regulatory bodies where we are
          legally required to do so.
        </p>
        <p>
          We do not share your data with advertisers, data brokers, or any other third parties.
        </p>
      </Section>

      <Section heading="5. How long we keep your data">
        <Ul items={[
          "Booking records: 2 years from the date of service, for legal and dispute purposes",
          "Account and profile data: for as long as you use the platform, or up to 2 years after your last booking",
          "Support messages: 1 year from the date of the conversation",
          "Payment references: 6 years, in line with standard tax record-keeping requirements",
        ]} />
        <p>
          You can ask us to delete your data at any time (see Your Rights below). Where data must
          be kept for legal or tax compliance, we will retain only what is required and delete the
          rest.
        </p>
        <ReviewNote>
          Confirm the appropriate retention periods with a lawyer, particularly the 6-year figure
          for payment references against FIRS requirements. The NDPA also has specific rules on
          retention that should be verified.
        </ReviewNote>
      </Section>

      <Section heading="6. Keeping your data safe">
        <p>We protect your data through:</p>
        <Ul items={[
          "Encrypted connections (HTTPS) across the entire platform",
          "Role-based access controls so only authorised team members can access customer data",
          "Secure database hosting with access logging",
          "No storage of sensitive payment information on our own servers",
        ]} />
        <p>
          No system is completely secure. If we become aware of a data breach that may affect
          you, we will notify you promptly and take steps to contain the situation.
        </p>
        <ReviewNote>
          The NDPA requires notification of personal data breaches to the NDPC within 72 hours of
          becoming aware. Ensure an incident response procedure is documented and in place before
          launch, including who internally is responsible for breach detection and reporting.
        </ReviewNote>
      </Section>

      <Section heading="7. Your rights">
        <p>Under the Nigeria Data Protection Act 2023, you have the right to:</p>
        <Ul items={[
          "Access a copy of the personal data we hold about you",
          "Ask us to correct any inaccurate or incomplete data",
          "Ask us to delete your data, subject to our legal retention obligations",
          "Object to us processing your data for direct marketing purposes",
          "Withdraw consent where our processing is based on your consent",
          "Lodge a complaint with the Nigeria Data Protection Commission (NDPC) at ndpc.gov.ng",
        ]} />
        <p>
          To exercise any of these rights, email us. We will respond within 30 days of receiving
          your request.
        </p>
      </Section>

      <Section heading="8. Cookies">
        <p>
          Our website uses only the cookies that are strictly necessary for it to function, such as
          keeping you signed in and remembering your booking progress between steps. We do not use
          advertising cookies, tracking pixels, or third-party analytics that follow you across
          other websites.
        </p>
        <ReviewNote>
          If any analytics or advertising tools are added to the platform later, this section must
          be updated and a cookie consent mechanism added where required.
        </ReviewNote>
      </Section>

      <Section heading="9. Third-party links">
        <p>
          Our website may contain links to third-party sites (for example, Paystack&apos;s payment pages).
          Once you leave the Klova platform, this privacy policy no longer applies. We recommend
          reading the privacy policies of any third-party sites you visit.
        </p>
      </Section>

      <Section heading="10. Children">
        <p>
          Klova is intended for people aged 18 and over. We do not knowingly collect personal
          data from anyone under 18. If you believe a child has registered on the platform,
          please contact us and we will delete the account.
        </p>
      </Section>

      <Section heading="11. International data transfers">
        <p>
          Some of the third-party services we use (including Supabase, Vercel, and Termii) may
          store or process data outside Nigeria. Where this occurs, we take steps to ensure the
          receiving country or organisation provides an adequate level of data protection.
        </p>
        <ReviewNote>
          The NDPA places restrictions on transferring personal data outside Nigeria. A lawyer
          should confirm whether the current set of service providers is compliant, and whether
          standard contractual clauses or other safeguards are required.
        </ReviewNote>
      </Section>

      <Section heading="12. Changes to this policy">
        <p>
          We may update this policy from time to time. The date at the top of this page shows
          when it was last revised. For significant changes, we will let you know by email before
          they take effect.
        </p>
      </Section>

      <Section heading="13. Contact us">
        <p>
          For questions, access requests, or complaints about how we handle your data, email us at{" "}
          <a href={emailHref} className="underline underline-offset-2" style={{ color: "var(--color-primary)" }}>
            {emailDisplay}
          </a>.
        </p>
        <p>
          If you are not satisfied with our response, you may contact the Nigeria Data Protection
          Commission at{" "}
          <a href="https://ndpc.gov.ng" className="underline underline-offset-2" style={{ color: "var(--color-primary)" }} target="_blank" rel="noopener noreferrer">
            ndpc.gov.ng
          </a>.
        </p>
        <ReviewNote>
          Update the support email address before launch. Confirm whether a named DPO contact is
          required and add their details here if so.
        </ReviewNote>
      </Section>

    </LegalShell>
  );
}
